### ISSUE TITLE
Can't host on Netlify

### ISSUE THREAD

**Issue by ajmalafif** [sandoche/Jekyll-webpack-boilerplate#1]
Hi @sandoche, 

Thanks for this super awesome project! I tried Deploy on Netlify but seems like there's an error:

```
2:09:32 AM: Either installing with `--full-index` or running `bundle update nokogiri` should
2:09:32 AM: fix the problem.
2:09:32 AM: In Gemfile:
2:09:32 AM:   amp-jekyll was resolved to 1.0.2, which depends on
2:09:32 AM:     nokogiri
2:09:32 AM: Error during gem install
2:09:32 AM: Error running command: Build script returned non-zero exit code: 1
2:09:33 AM: Failing build: Failed to build site
2:09:33 AM: failed during stage 'building site': Build script returned non-zero exit code: 1
2:09:33 AM: Finished processing build request in 27.549211835s
```
and these are the deploy settings:

Build command `npm run-script build`
Publish directory `_site/`
Production branch `master`

Any help?

**Comment by sandoche** [comment]
Can you try to replace the Gemfile and Gemfile.lock from the one of this commit: https://github.com/sandoche/Jekyll-webpack-boilerplate/tree/b4bd700c7bd35c74efc86ab119d818c10e00e608

Maybe it's due to the upgrade of the dependencies I made recently.

**Comment by ajmalafif** [comment]
@sandoche oh it works now! thanks for the super quick reply too!

So if I understood this correctly, I can't build the site into static pages and then deploy right?

**Comment by sandoche** [comment]
Actually you can but I haven't tried it since I updated the GEM dependencies. I will have a look and fix this issue. The problem with the previous version of nokogiri is that github was alerting that there were vulnarabilities.

**Comment by sandoche** [comment]
It's even better now you can use this button:
[![Deploy to Netlify](https://www.netlify.com/img/deploy/button.svg)](https://app.netlify.com/start/deploy?repository=https://github.com/sandoche/Jekyll-webpack-boilerplate)

Here is a demo of the Netlify build: https://dazzling-swartz-9738b5.netlify.com
