### ISSUE TITLE
Problem including jQuery plugin

### ISSUE THREAD

**Issue by malmr** [sandoche/Jekyll-webpack-boilerplate#10]
Hey,

thank you very much for your helpful boilerplate. Im facing a problem when I try to use jQuery in the `navigation.html` file, the console outputs 

> ReferenceError: $ is not defined

I installed jQuery with `npm i jquery --save`. Then I adjusted the `config/webpack.common.js` by adding:
> const webpack = require('webpack');
> ...
>   plugins: [   
>     new webpack.ProvidePlugin({
>       $: 'jquery',
>       jQuery: 'jquery'
>     }),

I also tried to use jQuery in the `index.js` file, but resulting in the same error.
What am I missing?
Thanks in advance!

**Comment by shashankshandilyav** [comment]
Same problem here. Thanks in advance

**Comment by sandoche** [comment]
Have you tried restarting the dev server?
Does the use of 'jquery' without the '$' works?

Here they say that you also need to put this in your index.js
```
import $ from 'jquery';  
window.jQuery = $; window.$ = $;
```
https://github.com/webpack/webpack/issues/4258

**Comment by malmr** [comment]
Thank you @sandoche. With this config im getting following error: 
_window is not defined_
But this can simply be [fixed by adjusting eslintrc.js](https://stackoverflow.com/a/32481806):
```
const config = {
  "extends": "airbnb-base",
  "env": {
    "browser": true,
    "node": true,
    "jasmine": true
  },
};
```
