### ISSUE TITLE
Where do I put _posts after removing jekyll-multiple-languages-plugin

### ISSUE THREAD

**Issue by keligijus** [sandoche/Jekyll-webpack-boilerplate#18]
I've deleted "jekyll-multiple-languages-plugin" from gemfile and `_config.yml`.

If I `_posts` in `_i18n` nothing happens. If I put it in a corresponding language folder, nothing happens. If I put it in the root, I get an error `Cannot GET /`.

**Comment by sandoche** [comment]
Hi,

Be sure you deleted all the templates calling the translations, also by default the about.md is loading a translation:
https://github.com/sandoche/Jekyll-webpack-boilerplate#internationalization

You should check the console there should be a detailed error followed by the exit of jekyll.

**Comment by keligijus** [comment]
Hi, thanks for your response. It turns out putting `_posts` in root folder works well. 

I think this was caused by Webpack trying to import images that did not exist.

**Comment by sandoche** [comment]
Perfect !
