### ISSUE TITLE
Bug: for imagemin-Webpack-pluning !

### ISSUE THREAD

**Issue by francoislesenne** [sandoche/Jekyll-webpack-boilerplate#2]
I encountered a bug in the package.json file with the version of imagemin-Webpack-pluning. 
On npm, it offers version 1.5.0-beta.1.
It's OK for me!
Thank you for your project

**Comment by sandoche** [comment]
I tried again and I didn't have any problem.
But maybe by updating npm dependencies or your node version should fix the problem.
