### ISSUE TITLE
Webpack Configuration Error

### ISSUE THREAD

**Issue by MikaCaldera** [sandoche/Jekyll-webpack-boilerplate#24]
Created a new github repo of the project. Starting the project from a clone. Followed the directions in the README.md.  I keep getting an error before making any real changes. 

#### Setup: 

I've tired  

node 10 and node 12 on to separate clean repos

###### Commands: 
```Run yarn install
Bundler install 
Run yarn build to start the development server (or use yarn start).```

It usually asks me to install webpack cli 

` yarn add -D webpack-cli`

Then on yarn start it breaks. 

``` ｢wds｣: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'mode'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           mode: ...
         }
       })
     ]
webpack-dev-server --env=dev exited with code ```

**Comment by sandoche** [comment]
Have you tried with `npm start` instead of `yarn start` ?

**Comment by sandoche** [comment]
And don't delete the `package-lock.json`

**Comment by MikaCaldera** [comment]
@sandoche Sorry for the late response. 

My project manager prefers I use yarn. (I'm personally indifferent) 
Started a new repo and didn't delete package.json. 

The only "_fix_" I could find was to change following lines in package.json

    ` "webpack-dev-server": "^3.1.11", `

I ended up downgrading it to `   "webpack-dev-server": "^2.6.1",`

It's the only way I can move away from that error. Do you figure it's an yarn vs npm issue? I can't imagine that being it because they are supposed to be interchangeable.  I

**Comment by sandoche** [comment]
It's a yarn.lock issue because it's missing the dependencies get mixed.
So better check package-json.lock you can find the best versions of everything!
