### ISSUE TITLE
Missing script

### ISSUE THREAD

**Issue by danieldeicide** [sandoche/Jekyll-webpack-boilerplate#3]
Hi! 
I've downloaded the repo, installed dependencies, everything good except when I run yarn start I get 
``` js
npm run-script clean:project; concurrently "webpack --env=dev --progress --profile --colors; webpack-dev-server --env=dev" "bundle exec jekyll serve"
npm ERR! missing script: clean:project;
```

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Daniel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run-script',
1 verbose cli   'clean:project;',
1 verbose cli   'concurrently',
1 verbose cli   'webpack --env=dev --progress --profile --colors; webpack-dev-server --env=dev',
1 verbose cli   'bundle exec jekyll serve' ]
2 info using npm@5.8.0
3 info using node@v8.5.0
4 verbose stack Error: missing script: clean:project;
4 verbose stack     at run (C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:151:19)
4 verbose stack     at C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:61:5
4 verbose stack     at C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:115:5
4 verbose stack     at C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:418:5
4 verbose stack     at checkBinReferences_ (C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:373:45)
4 verbose stack     at final (C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:416:3)
4 verbose stack     at then (C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:280:12
4 verbose stack     at C:\Users\Daniel\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:514:3)
5 verbose cwd C:\Users\Daniel\Downloads\99Designs\Jekyll-webpack-boilerplate-master
6 verbose Windows_NT 6.1.7601
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Daniel\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run-script" "clean:project;" "concurrently" "webpack --env=dev --progress --profile --colors; webpack-dev-server --env=dev" "bundle exec jekyll serve"
8 verbose node v8.5.0
9 verbose npm  v5.8.0
10 error missing script: clean:project;
11 verbose exit [ 1, true ]

**Comment by sandoche** [comment]
Hello,

There are problems with the boilerplate and windows.
I didn't spend much time to try to fix it. If you have ubuntu (or the ubuntu in windows) better go for it.

If you find a way to fix it for Windows, please send a PR.

**Comment by sandoche** [comment]
I just tried with Ubuntu bash inside Windows 10 (available in Microsoft Store) and it works perfectly.

**Comment by sandoche** [comment]
It now works with windows even without ubuntu bash: https://github.com/sandoche/Jekyll-webpack-boilerplate/pull/8
