### ISSUE TITLE
how to use _data folder?

### ISSUE THREAD

**Issue by thinkv** [sandoche/Jekyll-webpack-boilerplate#4]
Hello, this is great and I am attempting to start a website with it, my only concern is how can I use the standard jekyll _data folder for common variables?

I attempted to remove the language plugin but got a bit lost after this as it wasn't reading the data folder so I was left without the yml files.

**Comment by sandoche** [comment]
Hello, Thanks,

It is totally doable to use the `_data` folder.

Two solutions:
1. Just create it and use it without deleting the  `_i18n` folder.
2. Delete the `i18n` plugin and folder.

The first solution is the fastest.

To delete the i18n plugin here is the process:
1. Delete `gem 'jekyll-multiple-languages-plugin'` from `Gemfile`.
2. Delete `- jekyll-multiple-languages-plugin` from `_config`.
3. Delete the `_i18n` folder.
4. Remove all the liquid function like this one `{% t variable_name %}` from the `_include` and `_layout` folders (so `footer.html`, 'home.html', and maybe some others)
5. Delete `about.md`
6. Then run `npm start` and check the logs it will tell you if the `{% t variable_name %}` tag is still somewhere else

**Comment by thinkv** [comment]
I tried solution 1, however none of my site.data variables are being read when placing yml files in the _data folder?

**Comment by thinkv** [comment]
Tried again with a fresh pull, followed the process and added the _data folder, but variables aren't being read.

**Comment by sandoche** [comment]
- Are you getting any error in the console? Try just to run `jekyll serve` to only see jekyll related errors
- Are you sure you are writting them properly (with `{{ site.data.file_name.variable_path }}`) ? Here is an example below.
```
# For a file called strings.yml in the folder _data
header:
  title: Hello world

# In the layout home.html
<h1>{{ site.data.strings.header.title }}</h1>
```

**Comment by thinkv** [comment]
Thanks mate, not sure what was happening but it's working now :) appreciate the help.

**Comment by sandoche** [comment]
You're welcome.
I just created a telegram group: https://t.me/JekyllWebpack
